# 注：自用插件。
# 如果你是个闲的没事莫名其妙翻到这个项目的人，我要告诉你，我并没有对非法输入做特殊处理。如果你设成0/负数可能导致无法完成附魔，如果你设成大于39的数，那么又会变回过于昂贵。



# 铁砧最大允许成本 (1-39)
max-repair-cost: 38

# 是否允许无限(Infinity)和经验修补(Mending)共存
allow-infinity-mending: true

# 合并无限和经验修补所需要的成本（1~39）
infinity-mending-cost: 30

