name: FuckTooExpensive
version: '1.0.0'
main: com.arona.meow.FuckTooExpensive
api-version: '1.21'
author: AronaMeow_
folia-supported: true
description: Remove anvil "too expensive" limit and allow infinity+mending
